#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd -P)"

output_dir="${ROOT_DIR}/dist"
output_path="${output_dir}/safehouse.sh"
default_policy_path="${output_dir}/safehouse.generated.sb"
apps_policy_path="${output_dir}/safehouse-for-apps.generated.sb"
output_path_explicit=0
output_dir_explicit=0

GENERATOR="${ROOT_DIR}/bin/safehouse.sh"
template_root="/tmp/agent-safehouse-static-template"
template_home="${template_root}/home"
template_workdir="${template_root}/workspace"

profile_files=()

usage() {
  cat <<USAGE
Usage:
  $(basename "$0") [--output PATH] [--output-dir PATH]

Description:
  Generate all committed dist artifacts:
    - safehouse.sh (single-file executable with embedded profiles/runtime)
    - safehouse.generated.sb (default static policy)
    - safehouse-for-apps.generated.sb (--enable=macos-gui,electron)

Options:
  --output PATH
      Dist executable output file path (default: ${output_path})

  --output-dir PATH
      Directory for static policy outputs (default: ${output_dir})

  -h, --help
      Show this help
USAGE
}

to_abs_path() {
  local path="$1"

  if [[ "$path" == /* ]]; then
    printf '%s\n' "$path"
  else
    printf '%s/%s\n' "$ROOT_DIR" "$path"
  fi
}

collect_profiles() {
  local rel_path

  while IFS= read -r rel_path; do
    profile_files+=("$rel_path")
  done < <(
    cd "$ROOT_DIR"
    find profiles -type f -name '*.sb' | LC_ALL=C sort
  )
}

count_profiles_with_prefix() {
  local prefix="$1"
  local count=0
  local profile

  for profile in "${profile_files[@]}"; do
    if [[ "$profile" == "${prefix}"* ]]; then
      count=$((count + 1))
    fi
  done

  printf '%s\n' "$count"
}

validate_profiles() {
  local required_path listed_path found
  local -a required=(
    "profiles/00-base.sb"
    "profiles/10-system-runtime.sb"
    "profiles/20-network.sb"
  )

  for required_path in "${required[@]}"; do
    found=0
    for listed_path in "${profile_files[@]}"; do
      if [[ "$listed_path" == "$required_path" ]]; then
        found=1
        break
      fi
    done

    if [[ "$found" -ne 1 ]]; then
      echo "Missing required profile file: ${required_path}" >&2
      exit 1
    fi
  done

  if [[ "$(count_profiles_with_prefix "profiles/30-toolchains/")" -eq 0 ]]; then
    echo "No toolchain profiles found under profiles/30-toolchains" >&2
    exit 1
  fi

  if [[ "$(count_profiles_with_prefix "profiles/40-agents/")" -eq 0 ]]; then
    echo "No agent profiles found under profiles/40-agents" >&2
    exit 1
  fi

  if [[ "$(count_profiles_with_prefix "profiles/50-integrations/")" -eq 0 ]]; then
    echo "No integration profiles found under profiles/50-integrations" >&2
    exit 1
  fi
}

marker_for_path() {
  local rel_path="$1"
  local marker="${rel_path//\//_}"
  marker="${marker//./_}"
  marker="${marker//-/_}"
  printf '__SAFEHOUSE_EMBEDDED_%s__' "$marker"
}

resolve_output_paths() {
  if [[ "$output_path_explicit" -eq 1 ]]; then
    output_path="$(to_abs_path "$output_path")"
  fi

  if [[ "$output_dir_explicit" -eq 1 ]]; then
    output_dir="$(to_abs_path "$output_dir")"
  fi

  if [[ "$output_path_explicit" -eq 0 && "$output_dir_explicit" -eq 1 ]]; then
    output_path="${output_dir%/}/safehouse.sh"
  fi

  output_path="$(to_abs_path "$output_path")"
  output_dir="$(to_abs_path "$output_dir")"
  default_policy_path="${output_dir%/}/safehouse.generated.sb"
  apps_policy_path="${output_dir%/}/safehouse-for-apps.generated.sb"
}

emit_banner() {
  local source_commit="$1"

  cat <<SCRIPT
#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Agent Safehouse Dist Binary (generated file)
# Source Commit: ${source_commit}
# Generated by: scripts/generate-dist.sh
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT
}

emit_array_declaration() {
  local name="$1"
  shift

  printf '%s=(\n' "$name"
  local item
  for item in "$@"; do
    printf '  "%s"\n' "$item"
  done
  printf ')\n\n'
}

emit_embedded_profiles_function() {
  local rel_path marker

  cat <<'SCRIPT'
embedded_profile_body() {
  case "$1" in
SCRIPT

  for rel_path in "${profile_files[@]}"; do
    marker="$(marker_for_path "$rel_path")"
    printf '    "%s")\n' "$rel_path"
    printf "      cat <<'%s'\n" "$marker"
    cat "${ROOT_DIR}/${rel_path}"
    if [[ -n "$(tail -c 1 "${ROOT_DIR}/${rel_path}" 2>/dev/null || true)" ]]; then
      echo ""
    fi
    printf '%s\n' "$marker"
    printf '      ;;\n'
  done

  cat <<'SCRIPT'
    *)
      return 1
      ;;
  esac
}

SCRIPT
}

emit_safehouse_globals() {
  awk '
    NR <= 2 { next }
    /^# shellcheck source=bin\/lib\/common.sh$/ { exit }
    { print }
  ' "${ROOT_DIR}/bin/safehouse.sh"

  echo ""
}

emit_inlined_runtime_sources() {
  cat "${ROOT_DIR}/bin/lib/common.sh"
  echo ""
  cat "${ROOT_DIR}/bin/lib/policy.sh"
  echo ""
  cat "${ROOT_DIR}/bin/lib/cli.sh"
  echo ""
}

emit_embedded_overrides() {
  cat <<'SCRIPT'
profile_key_from_source() {
  local source="$1"

  if [[ "$source" == profiles/* ]]; then
    printf '%s\n' "$source"
    return
  fi

  if [[ -n "${PROFILES_DIR:-}" && "$source" == "${PROFILES_DIR}/"* ]]; then
    printf 'profiles/%s\n' "${source#"${PROFILES_DIR}/"}"
    return
  fi

  printf '%s\n' "$source"
}

append_profile() {
  local target="$1"
  local source="$2"
  local key

  key="$(profile_key_from_source "$source")"
  if ! embedded_profile_body "$key" >> "$target"; then
    echo "Missing profile module: ${source}" >&2
    exit 1
  fi
  echo "" >> "$target"
}

append_resolved_base_profile() {
  local target="$1"
  local source="$2"
  local escaped_home key

  escaped_home="$(escape_for_sb "$home_dir")"
  key="$(profile_key_from_source "$source")"

  if ! embedded_profile_body "$key" | awk -v home="$escaped_home" -v token="$HOME_DIR_TEMPLATE_TOKEN" '
    BEGIN { replaced = 0 }
    {
      line = $0
      count = gsub(token, home, line)
      if (count > 0) {
        replaced = 1
      }
      print line
    }
    END {
      if (replaced == 0) {
        exit 64
      }
    }
  ' >> "$target"; then
    echo "Failed to resolve HOME_DIR placeholder in base profile: ${source}" >&2
    echo "Expected HOME_DIR placeholder token: ${HOME_DIR_TEMPLATE_TOKEN}" >&2
    exit 1
  fi

  echo "" >> "$target"
}

append_all_module_profiles() {
  local target="$1"
  local base_dir="$2"
  local found_any=0
  local key profile_prefix

  case "$base_dir" in
    "${PROFILES_DIR}/30-toolchains"|"profiles/30-toolchains")
      profile_prefix="profiles/30-toolchains/"
      ;;
    "${PROFILES_DIR}/40-agents"|"profiles/40-agents")
      profile_prefix="profiles/40-agents/"
      ;;
    *)
      echo "No module profiles found in: ${base_dir}" >&2
      exit 1
      ;;
  esac

  for key in "${PROFILE_KEYS[@]}"; do
    [[ "$key" == "${profile_prefix}"* ]] || continue
    found_any=1
    append_profile "$target" "$key"
  done

  if [[ "$found_any" -eq 0 ]]; then
    echo "No module profiles found in: ${base_dir}" >&2
    exit 1
  fi
}

append_integration_profiles() {
  local target="$1"
  local base_dir="$2"
  local key base_name
  local found_any=0
  local added_any=0

  local -a opt_in_integrations=()
  if [[ "$enable_docker_integration" -ne 1 ]]; then
    opt_in_integrations+=("docker")
  fi
  if [[ "$enable_macos_gui_integration" -ne 1 ]]; then
    opt_in_integrations+=("macos-gui")
  fi
  if [[ "$enable_electron_integration" -ne 1 ]]; then
    opt_in_integrations+=("electron")
  fi

  if [[ "${#opt_in_integrations[@]}" -gt 0 ]]; then
    echo ";; Opt-in integrations not enabled: ${opt_in_integrations[*]}" >> "$target"
    echo ";; Use --enable=<feature> (comma-separated) to include them." >> "$target"
    echo ";; Note: --enable=electron also enables macos-gui." >> "$target"
    echo "" >> "$target"
  fi

  echo ";; Threat-model note: blocking exfiltration/C2 is explicitly NOT a goal for this sandbox." >> "$target"
  echo "" >> "$target"

  case "$base_dir" in
    "${PROFILES_DIR}/50-integrations"|"profiles/50-integrations")
      ;;
    *)
      echo "No integration profiles found in: ${base_dir}" >&2
      exit 1
      ;;
  esac

  for key in "${PROFILE_KEYS[@]}"; do
    [[ "$key" == "profiles/50-integrations/"* ]] || continue
    found_any=1

    base_name="$(basename "$key")"
    if [[ "$base_name" == "docker.sb" && "$enable_docker_integration" -ne 1 ]]; then
      continue
    fi
    if [[ "$base_name" == "macos-gui.sb" && "$enable_macos_gui_integration" -ne 1 ]]; then
      continue
    fi
    if [[ "$base_name" == "electron.sb" && "$enable_electron_integration" -ne 1 ]]; then
      continue
    fi

    added_any=1
    append_profile "$target" "$key"
  done

  if [[ "$found_any" -eq 0 ]]; then
    echo "No integration profiles found in: ${base_dir}" >&2
    exit 1
  fi

  if [[ "$added_any" -eq 0 ]]; then
    echo "No enabled integration profiles found in: ${base_dir}" >&2
    exit 1
  fi
}

SCRIPT
}

generate_static_policy_files() {
  if [[ ! -x "$GENERATOR" ]]; then
    echo "Policy generator is missing or not executable: ${GENERATOR}" >&2
    exit 1
  fi

  mkdir -p "$output_dir" "$template_home" "$template_workdir"

  (
    cd "$template_workdir"
    HOME="$template_home" "$GENERATOR" --output "$default_policy_path" >/dev/null
    HOME="$template_home" "$GENERATOR" --enable=macos-gui,electron --output "$apps_policy_path" >/dev/null
  )

  chmod 0644 "$default_policy_path" "$apps_policy_path"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 1; }
      output_path="$2"
      output_path_explicit=1
      shift 2
      ;;
    --output=*)
      output_path="${1#*=}"
      output_path_explicit=1
      shift
      ;;
    --output-dir)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 1; }
      output_dir="$2"
      output_dir_explicit=1
      shift 2
      ;;
    --output-dir=*)
      output_dir="${1#*=}"
      output_dir_explicit=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

resolve_output_paths

collect_profiles
validate_profiles

source_commit="$(git -C "$ROOT_DIR" rev-parse --verify HEAD 2>/dev/null || printf 'unknown')"

mkdir -p "$(dirname "$output_path")"
tmp_output="$(mktemp "${output_path}.XXXXXX")"

cleanup_tmp() {
  rm -f "$tmp_output"
}
trap cleanup_tmp EXIT

{
  emit_banner "$source_commit"
  emit_array_declaration "PROFILE_KEYS" "${profile_files[@]}"
  emit_embedded_profiles_function
  emit_safehouse_globals
  emit_inlined_runtime_sources
  emit_embedded_overrides
  echo 'main "$@"'
} > "$tmp_output"

chmod 0755 "$tmp_output"
mv "$tmp_output" "$output_path"
trap - EXIT

generate_static_policy_files

printf '%s\n' "$output_path"
printf '%s\n' "$default_policy_path"
printf '%s\n' "$apps_policy_path"
